# Generated by Django 4.0.3 on 2022-03-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id_author',
        ),
        migrations.RemoveField(
            model_name='author',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='video',
            name='id_author',
        ),
        migrations.AddField(
            model_name='video',
            name='sec_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
