# Generated by Django 4.0.3 on 2022-03-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_author_id_author_remove_author_nickname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
